[package]
name = "realm"
version = "1.3.0"
authors = ["zhboner <zhboner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
futures = "0.3"

clap = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "1", features = ["full"] }
trust-dns-resolver = "0.20"

lazy_static = "1"